//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_RequestSimulator.ClienteRequest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetodoBuscaTaxi", Namespace="http://schemas.datacontract.org/2004/07/TCC_Application")]
    public enum MetodoBuscaTaxi : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GPS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BROADCASTING = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISTANCIA_EUCLIDIANA = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTIMIZACAO = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectionsPoco", Namespace="http://schemas.datacontract.org/2004/07/TCC_Application")]
    [System.SerializableAttribute()]
    public partial class DirectionsPoco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceInMetersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DurationInTrafficField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ProcessTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUS_CODEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DistanceInMeters {
            get {
                return this.DistanceInMetersField;
            }
            set {
                if ((this.DistanceInMetersField.Equals(value) != true)) {
                    this.DistanceInMetersField = value;
                    this.RaisePropertyChanged("DistanceInMeters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan DurationInTraffic {
            get {
                return this.DurationInTrafficField;
            }
            set {
                if ((this.DurationInTrafficField.Equals(value) != true)) {
                    this.DurationInTrafficField = value;
                    this.RaisePropertyChanged("DurationInTraffic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ProcessTime {
            get {
                return this.ProcessTimeField;
            }
            set {
                if ((this.ProcessTimeField.Equals(value) != true)) {
                    this.ProcessTimeField = value;
                    this.RaisePropertyChanged("ProcessTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS_CODE {
            get {
                return this.STATUS_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUS_CODEField, value) != true)) {
                    this.STATUS_CODEField = value;
                    this.RaisePropertyChanged("STATUS_CODE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteRequest.IClienteRequest")]
    public interface IClienteRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRequest/RequisitarTaxi", ReplyAction="http://tempuri.org/IClienteRequest/RequisitarTaxiResponse")]
        TCC_RequestSimulator.ClienteRequest.DirectionsPoco RequisitarTaxi(System.Guid codigoCliente, double latitude, double longitude, TCC_RequestSimulator.ClienteRequest.MetodoBuscaTaxi metodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRequest/AlterarStatusTaxistaAleatorio", ReplyAction="http://tempuri.org/IClienteRequest/AlterarStatusTaxistaAleatorioResponse")]
        void AlterarStatusTaxistaAleatorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteRequest/MovimentarTaxistas", ReplyAction="http://tempuri.org/IClienteRequest/MovimentarTaxistasResponse")]
        void MovimentarTaxistas();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteRequestChannel : TCC_RequestSimulator.ClienteRequest.IClienteRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteRequestClient : System.ServiceModel.ClientBase<TCC_RequestSimulator.ClienteRequest.IClienteRequest>, TCC_RequestSimulator.ClienteRequest.IClienteRequest {
        
        public ClienteRequestClient() {
        }
        
        public ClienteRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TCC_RequestSimulator.ClienteRequest.DirectionsPoco RequisitarTaxi(System.Guid codigoCliente, double latitude, double longitude, TCC_RequestSimulator.ClienteRequest.MetodoBuscaTaxi metodo) {
            return base.Channel.RequisitarTaxi(codigoCliente, latitude, longitude, metodo);
        }
        
        public void AlterarStatusTaxistaAleatorio() {
            base.Channel.AlterarStatusTaxistaAleatorio();
        }
        
        public void MovimentarTaxistas() {
            base.Channel.MovimentarTaxistas();
        }
    }
}
