//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCC_Web.App_LocalResources.LabelsResource", typeof(LabelsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação.
        /// </summary>
        public static string AUTENTICACAO {
            get {
                return ResourceManager.GetString("AUTENTICACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro.
        /// </summary>
        public static string CADASTRO {
            get {
                return ResourceManager.GetString("CADASTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ERRO {
            get {
                return ResourceManager.GetString("ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição de Taxi.
        /// </summary>
        public static string REQUISICAO {
            get {
                return ResourceManager.GetString("REQUISICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione...
        /// </summary>
        public static string SELECIONE {
            get {
                return ResourceManager.GetString("SELECIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string TITULO {
            get {
                return ResourceManager.GetString("TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo.
        /// </summary>
        public static string VEICULO {
            get {
                return ResourceManager.GetString("VEICULO", resourceCulture);
            }
        }
    }
}
