//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCC_Web.App_LocalResources.MensagensResource", typeof(MensagensResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendimento de Requisição.
        /// </summary>
        public static string ATENDIMENTO_REQUISICAO {
            get {
                return ResourceManager.GetString("ATENDIMENTO_REQUISICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro realizado com sucesso..
        /// </summary>
        public static string CADASTRO_SUCESSO {
            get {
                return ResourceManager.GetString("CADASTRO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente cancelou a requisição!.
        /// </summary>
        public static string CLIENTE_CANCELOU_REQUISICAO {
            get {
                return ResourceManager.GetString("CLIENTE_CANCELOU_REQUISICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de geolocalização indisponível. Por favor, tente novamente!.
        /// </summary>
        public static string GEOLOCALIZACAO_INDISPONIVEL {
            get {
                return ResourceManager.GetString("GEOLOCALIZACAO_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar posição geográfica a partir do endereço fornecido!.
        /// </summary>
        public static string GEOLOCALIZACAO_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("GEOLOCALIZACAO_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos..
        /// </summary>
        public static string LOGIN_NAO_REALIZADO {
            get {
                return ResourceManager.GetString("LOGIN_NAO_REALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minha Posição Atual.
        /// </summary>
        public static string MINHA_POSICAO_ATUAL {
            get {
                return ResourceManager.GetString("MINHA_POSICAO_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum taxi disponível encontrado!.
        /// </summary>
        public static string NENHUM_TAXI_DISPONIVEL {
            get {
                return ResourceManager.GetString("NENHUM_TAXI_DISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processamento de Requisição.
        /// </summary>
        public static string PROCESSAMENTO_REQUISICAO {
            get {
                return ResourceManager.GetString("PROCESSAMENTO_REQUISICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando Requisição.
        /// </summary>
        public static string PROCESSANDO_REQUISICAO {
            get {
                return ResourceManager.GetString("PROCESSANDO_REQUISICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição cancelada..
        /// </summary>
        public static string REQUISICAO_CANCELADA {
            get {
                return ResourceManager.GetString("REQUISICAO_CANCELADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendimento concluido..
        /// </summary>
        public static string REQUISICAO_CONCLUIDA {
            get {
                return ResourceManager.GetString("REQUISICAO_CONCLUIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição recusada..
        /// </summary>
        public static string REQUISICAO_RECUSADA {
            get {
                return ResourceManager.GetString("REQUISICAO_RECUSADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuário para cadastro não foi definido..
        /// </summary>
        public static string TIPO_USUARIO_NAO_DEFINIDO {
            get {
                return ResourceManager.GetString("TIPO_USUARIO_NAO_DEFINIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo salvo com sucesso..
        /// </summary>
        public static string VEICULO_SUCESSO {
            get {
                return ResourceManager.GetString("VEICULO_SUCESSO", resourceCulture);
            }
        }
    }
}
