//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_Simulator.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.ITaxistaLocation")]
    public interface ITaxistaLocation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxistaLocation/AtualizarPosicao", ReplyAction="http://tempuri.org/ITaxistaLocation/AtualizarPosicaoResponse")]
        void AtualizarPosicao(System.Guid ID, double latitude, double longitude);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaxistaLocationChannel : TCC_Simulator.WebService.ITaxistaLocation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxistaLocationClient : System.ServiceModel.ClientBase<TCC_Simulator.WebService.ITaxistaLocation>, TCC_Simulator.WebService.ITaxistaLocation {
        
        public TaxistaLocationClient() {
        }
        
        public TaxistaLocationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxistaLocationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxistaLocationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxistaLocationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AtualizarPosicao(System.Guid ID, double latitude, double longitude) {
            base.Channel.AtualizarPosicao(ID, latitude, longitude);
        }
    }
}
