//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_RequestSimulator.TaxistaLocation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxistaLocation.ITaxistaLocation")]
    public interface ITaxistaLocation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxistaLocation/IniciarPosicaoComStatusAleatorio", ReplyAction="http://tempuri.org/ITaxistaLocation/IniciarPosicaoComStatusAleatorioResponse")]
        void IniciarPosicaoComStatusAleatorio(System.Guid ID, double latitude, double longitude);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaxistaLocationChannel : TCC_RequestSimulator.TaxistaLocation.ITaxistaLocation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxistaLocationClient : System.ServiceModel.ClientBase<TCC_RequestSimulator.TaxistaLocation.ITaxistaLocation>, TCC_RequestSimulator.TaxistaLocation.ITaxistaLocation {
        
        public TaxistaLocationClient() {
        }
        
        public TaxistaLocationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxistaLocationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxistaLocationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxistaLocationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void IniciarPosicaoComStatusAleatorio(System.Guid ID, double latitude, double longitude) {
            base.Channel.IniciarPosicaoComStatusAleatorio(ID, latitude, longitude);
        }
    }
}
